# \
CS 170 - Theory of Operating Systems\
By: Matthew S Montoya\
By: Matthew Iglesias\
Purpose: Evaluate First Fit, Next Fit, & Best Fit memory allocation strategies\
Last Modified: 17 April 2019

lab4.o: src.c allocate.c
	gcc src.c allocate.c -o lab4.o
	
clean:
	rm -f *.o